#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/expo@54.0.34_@babel+core@7._6d22cf553187b34cd4eb6dde1a4691dd/node_modules/expo/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/expo@54.0.34_@babel+core@7._6d22cf553187b34cd4eb6dde1a4691dd/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/expo@54.0.34_@babel+core@7._6d22cf553187b34cd4eb6dde1a4691dd/node_modules/expo/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/expo@54.0.34_@babel+core@7._6d22cf553187b34cd4eb6dde1a4691dd/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../expo/bin/autolinking" "$@"
else
  exec node  "$basedir/../expo/bin/autolinking" "$@"
fi
