
[build]
  command = "npx --prefix ./packages/client vite build"
  publish = "packages/client/dist"
  functions = "netlify-functions"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
