#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/react-native@0.81.5_@babel+_4a68080c39ca5aa23ef78d3bf89635fd/node_modules/react-native/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/react-native@0.81.5_@babel+_4a68080c39ca5aa23ef78d3bf89635fd/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/react-native@0.81.5_@babel+_4a68080c39ca5aa23ef78d3bf89635fd/node_modules/react-native/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/react-native@0.81.5_@babel+_4a68080c39ca5aa23ef78d3bf89635fd/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../react-native/cli.js" "$@"
else
  exec node  "$basedir/../react-native/cli.js" "$@"
fi
