#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/vite@5.4.21_@types+node@20._2e59d6321a8215c5a965dc927467bb25/node_modules/vite/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/vite@5.4.21_@types+node@20._2e59d6321a8215c5a965dc927467bb25/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/vite@5.4.21_@types+node@20._2e59d6321a8215c5a965dc927467bb25/node_modules/vite/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/vite@5.4.21_@types+node@20._2e59d6321a8215c5a965dc927467bb25/node_modules:/mnt/c/Users/deanz/Downloads/Gather the Crown Creats and Foes/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../vite/bin/vite.js" "$@"
else
  exec node  "$basedir/../../../vite/bin/vite.js" "$@"
fi
